"""Tests for the Ollama HyDE example.

This module verifies the hypothetical document generation and embedding
flow end to end while mocking Ollama API responses. The test uses the
provider-agnostic ``init_chat_model`` helper to construct a chat model and
replaces the network-backed Ollama calls with deterministic fake data.

+----------------------------+------------------------------------------------+
| Test area                  | Mocked component                               |
+============================+================================================+
| Chat generation            | ``langchain_ollama.ChatOllama.invoke``          |
+----------------------------+------------------------------------------------+
| Embedding generation       | ``langchain_ollama.OllamaEmbeddings.embed_query`` |
+----------------------------+------------------------------------------------+
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any
from unittest.mock import patch

from langchain.chat_models import init_chat_model
from langchain_core.messages import AIMessage
from langchain_ollama import OllamaEmbeddings

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


def run_hyde_example(question: str, model_name: str = "llama3") -> dict[str, Any]:
    """Run the HyDE example using Ollama through ``init_chat_model``.

    Args:
        question: The user query to generate a hypothetical document for.
        model_name: The Ollama model name to use for chat and embeddings.

    Returns:
        A dictionary containing the generated hypothetical document and
        its corresponding embedding vector.

    +--------------------------+------------------------------------------+
    | Key                      | Description                              |
    +==========================+==========================================+
    | hypothetical_document    | Text generated by the chat model.        |
    +--------------------------+------------------------------------------+
    | embedding                | Vector embedding of the generated text.  |
    +--------------------------+------------------------------------------+
    """
    llm = init_chat_model(model=model_name, provider="ollama", temperature=0)
    prompt = (
        "Write a short hypothetical document that directly answers the "
        f"question: {question}"
    )
    response = llm.invoke(prompt)
    document = response.content if hasattr(response, "content") else str(response)

    embeddings = OllamaEmbeddings(model=model_name)
    embedding = embeddings.embed_query(document)

    return {"hypothetical_document": document, "embedding": embedding}


def test_hyde_example_end_to_end() -> None:
    """Verify the HyDE example with mocked Ollama chat and embeddings."""
    fake_document = "A hypothetical document explaining the answer."
    fake_embedding = [0.1, 0.2, 0.3, 0.4]

    with patch("langchain_ollama.ChatOllama.invoke", return_value=AIMessage(content=fake_document)) as mock_chat:
        with patch("langchain_ollama.OllamaEmbeddings.embed_query", return_value=fake_embedding) as mock_embed:
            result = run_hyde_example("What is LangChain?")

    mock_chat.assert_called_once()
    mock_embed.assert_called_once_with(fake_document)

    assert result["hypothetical_document"] == fake_document
    assert result["embedding"] == fake_embedding


def test_hyde_example_with_custom_model() -> None:
    """Verify that a custom Ollama model name is passed to the client."""
    fake_document = "Custom model response."
    fake_embedding = [0.5, 0.6]

    with patch("langchain_ollama.ChatOllama.invoke", return_value=AIMessage(content=fake_document)) as mock_chat:
        with patch("langchain_ollama.OllamaEmbeddings.embed_query", return_value=fake_embedding) as mock_embed:
            result = run_hyde_example("Custom question", model_name="llama3.1")

    mock_chat.assert_called_once()
    mock_embed.assert_called_once_with(fake_document)

    assert result["hypothetical_document"] == fake_document
    assert result["embedding"] == fake_embedding


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__]))
