"""
This example demonstrates how to create a basic LLMChain using LangChain.

Purpose:
    Show the minimal setup for chaining a prompt template with an LLM
    to generate a response. It uses `init_chat_model` to create a
    provider-agnostic chat model, so you can easily swap between
    different model providers by changing the model name and provider.

    The `create_chain` helper encapsulates the model, prompt template,
    and chain setup, making it easy to reuse the same configuration
    elsewhere in your code.

Usage:
    Set the API key for your chosen model provider (e.g., OPENAI_API_KEY
    for OpenAI), then run:
    python examples/01_basic_chains.py

Expected output:
    A short, friendly response about the importance of learning new things,
    generated by the configured LLM.
"""

from langchain.chat_models import init_chat_model
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain


def create_chain(
    model: str = "gpt-4o-mini",
    model_provider: str = "openai",
    temperature: float = 0.7,
) -> LLMChain:
    """Create and return a configured LLMChain for reuse."""
    llm = init_chat_model(model, model_provider=model_provider, temperature=temperature)

    prompt = PromptTemplate(
        input_variables=["topic"],
        template="Write a short, enthusiastic sentence about {topic}.",
    )

    return LLMChain(llm=llm, prompt=prompt)


def run_example():
    chain = create_chain()
    result = chain.run("learning new things")
    print(result)


if __name__ == "__main__":
    run_example()
