from langchain.llms import OpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain

"""
This example demonstrates how to create a basic LLMChain using LangChain.

Purpose:
    Show the minimal setup for chaining a prompt template with an LLM
    to generate a response.

Usage:
    Set the OPENAI_API_KEY environment variable, then run:
    python examples/01_basic_chains.py

Expected output:
    A short, friendly response about the importance of learning new things,
    generated by the configured LLM.
"""

llm = OpenAI(temperature=0.7)

prompt = PromptTemplate(
    input_variables=["topic"],
    template="Write a short, enthusiastic sentence about {topic}.",
)

chain = LLMChain(llm=llm, prompt=prompt)

if __name__ == "__main__":
    result = chain.run("learning new things")
    print(result)
