"""Use Ollama to generate a hypothetical document and retrieve relevant context.

+---------------------------+---------------------------------------------------------------+
| Goal                      | Demonstrate HyDE with Ollama.                                |
| Model                     | llama3.1 (configurable via OLLAMA_CHAT_MODEL)                 |
| Provider                  | Ollama                                                       |
| Embeddings                | OllamaEmbeddings                                             |
+---------------------------+---------------------------------------------------------------+
"""

import math
import os

from langchain.chat_models import init_chat_model
from langchain_ollama import OllamaEmbeddings
from langchain_core.prompts import ChatPromptTemplate


def cosine_similarity(vector_a, vector_b):
    """Compute the cosine similarity between two vectors."""
    dot_product = sum(a * b for a, b in zip(vector_a, vector_b))
    norm_a = math.sqrt(sum(a * a for a in vector_a))
    norm_b = math.sqrt(sum(b * b for b in vector_b))
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot_product / (norm_a * norm_b)


def generate_hypothetical_document(question, chat_model):
    """Generate a hypothetical document that would answer the given question."""
    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                "Write a short, factual document that directly answers the user's question. "
                "The document should be self-contained and informative.",
            ),
            ("human", "{question}"),
        ]
    )
    chain = prompt | chat_model
    response = chain.invoke({"question": question})
    return response.content


def retrieve_relevant_context(question, documents, chat_model, embeddings):
    """Generate a hypothetical document, embed it, and return the most relevant context."""
    hypothetical_doc = generate_hypothetical_document(question, chat_model)
    hypothetical_embedding = embeddings.embed_query(hypothetical_doc)
    doc_embeddings = embeddings.embed_documents(documents)

    scored_docs = []
    for doc, doc_embedding in zip(documents, doc_embeddings):
        score = cosine_similarity(hypothetical_embedding, doc_embedding)
        scored_docs.append((doc, score))

    scored_docs.sort(key=lambda pair: pair[1], reverse=True)
    return scored_docs, hypothetical_doc


def main():
    """Run the HyDE example with Ollama."""
    chat_model = init_chat_model(
        model=os.getenv("OLLAMA_CHAT_MODEL", "llama3.1"),
        provider="ollama",
        temperature=0.0,
        base_url=os.getenv("OLLAMA_BASE_URL", "http://localhost:11434"),
    )
    embeddings = OllamaEmbeddings(
        model=os.getenv("OLLAMA_EMBEDDINGS_MODEL", "nomic-embed-text"),
        base_url=os.getenv("OLLAMA_BASE_URL", "http://localhost:11434"),
    )

    documents = [
        "LangChain Expression Language (LCEL) is a declarative way to compose chains. "
        "It provides a unified interface for streaming, batching, and async operations.",
        "Agents in LangChain use a language model to decide which tools to call and in what order. "
        "They can iterate through multiple reasoning and action steps.",
        "Retrieval-augmented generation (RAG) combines a retrieval step with a generation step. "
        "Relevant documents are fetched from a vector store and passed to the model.",
        "Ollama allows running large language models locally. It exposes an OpenAI-compatible API "
        "and supports embedding models for semantic search.",
    ]

    question = "What is LangChain Expression Language?"

    try:
        scored_docs, hypothetical_doc = retrieve_relevant_context(
            question, documents, chat_model, embeddings
        )
    except Exception as exc:  # pragma: no cover - depends on external service
        print(f"Error running Ollama HyDE example: {exc}")
        return

    print("Question:", question)
    print("\nHypothetical document generated by Ollama:")
    print(hypothetical_doc)
    print("\nMost relevant context:")
    for doc, score in scored_docs[:2]:
        print(f"\nScore: {score:.4f}")
        print(doc)


if __name__ == "__main__":
    main()
